### ISSUE TITLE
Can I delete my project? :-)

### ISSUE THREAD

**Issue by matozoid** [daanvdh/JavaDataFlow#2]
Hi! I created this a while ago because people kept asking for data flow analysis. I don't really want to maintain it, so is your stuff better already? Can I delete my project? :-)

https://github.com/matozoid/java_flow_analyser

**Comment by daanvdh** [comment]
Hi, I took a quick look. Too bad that we both had to create the super big if-statement handling different types ;-) 

My project keeps track of owners (methods, classes) of flow nodes since it's typically important to scope 'until where' you want to follow the flow. It also allows following the flow forward and backward. On the other hand your project supports loops and choices, which mine doesn't (yet). In your project I also don't see any parsing of assign statements, so it really is only control flow and not data flow. 

I forked your project just in case you are going to delete it. I'll probably use it as input, once I find the time to model loops and choices. The current state is that both projects support a different part of the types in the JavaParser AST. 

I would propose for now that you keep the project. It would probably help others in finding my project if you could reference it.

**Comment by matozoid** [comment]
Alright, the project is still there and I put a suggestion in the readme to look here instead. Good luck and don't forget to look at the issue list for inspiration: https://github.com/matozoid/java_flow_analyser/issues
